### ISSUE TITLE
Houdini Version_creator error

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#18]
Hey eoyilmaz i have this error when run `version_creator()` in Houdini 16. 
pyside2 error!! 

```
>>> houdini.version_creator()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "\anima\anima\ui\scripts\houdini.py", line 56, in ve
rsion_creator
    from anima.ui import version_creator
  File "\anima\anima\ui\version_creator.py", line 13, in <m
odule>
    from anima.ui.base import AnimaDialogBase, ui_caller
  File "\anima\anima\ui\base.py", line 11, in <module>
    from anima.ui.utils import logger
  File "\anima\anima\ui\utils.py", line 12, in <module>
    from anima.ui.lib import QtCore, QtGui, QtWidgets
  File "\anima\anima\ui\lib.py", line 23, in <module>
    from PySide2 import QtGui, QtCore, QtWidgets
ImportError: No module named PySide2
```

**Comment by eoyilmaz** [comment]
Did you run it on Houdini 16 with PySide version.

**Comment by tws0002** [comment]
yes if I set it to PySide!! meaning in the `anima.ui.scripts.houdini `
```
import hou
from anima import logger

if hou.applicationVersion()[0] <= 15:
    from anima.ui import SET_PYSIDE
    from anima.utils import do_db_setup
    SET_PYSIDE()
else:
    from anima.ui import SET_PYSIDE2
    from anima.utils import do_db_setup
    SET_PYSIDE2()
```
PySide2 is not workable in houdini 16?

**Comment by tws0002** [comment]
after launch `version_creator()` here is another error pop up in the Houdini Console!! 
ERROR Message 
```
Qt Warn: QObject::startTimer: timers cannot be started from another thread
Qt Warn: QApplication: Object event filter cannot be in a different thread.
```
![qt warn error](https://user-images.githubusercontent.com/7018625/29866528-3d1a38a8-8dab-11e7-92e9-de19562fdfa4.jpg)

**Comment by eoyilmaz** [comment]
I'm on vacation now, will return to work next week. But the ``anima.ui.scripts.houdini`` should work without any problems under the normal installation of Houdini 16.

**Comment by tws0002** [comment]
I found out the error!! because I using Houdini Python shell to run `version_creator()`!!

**Comment by eoyilmaz** [comment]
So I'm closing this issue!
